### ISSUE TITLE
Images from cross origin not allowed ?

### ISSUE THREAD

**Issue by mate2** [SebastianAbel/lightbox360#1]
Hi,

i tried to use your lightbox to display 360 photos from a cross domain source, but i always got this error : 

`Uncaught DOMException: Failed to execute 'texImage2D' on 'WebGLRenderingContext': The cross-origin image at https://image.shutterstock.com/z/stock-photo-beautiful-degree-panorama-at-the-beach-of-masoala-national-park-madagascar-284490797.jpg may not be loaded.`

Is there a way to allow cross origin image ?

**Comment by SebastianAbel** [comment]
Hi,
should be fixed now for domains that support CORS.
See test.html which works now with your supplied image-link.
Fix is based on information from https://webglfundamentals.org/webgl/lessons/webgl-cors-permission.html

**Comment by mate2** [comment]
Hi Sebastian,

Works perfectly now ! 
Thank you, seems i didn't search enough ^^
